name = "ManualNLPModels"
uuid = "30dfa513-9b2f-4fb3-9796-781eabac1617"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com> and contributors"]
version = "0.1.1"

[deps]
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"

[compat]
NLPModels = "0.17, 0.18"
julia = "1.6"
